version: latest

services:
  backend:
    build: ./backend
    container_name: roomify_backend
    ports: ["4000:4000"]
    env_file: ./.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: roomify_frontend
    ports: ["5173:5173"]
    env_file: ./.env
    environment:
      - VITE_API_BASE=${VITE_API_BASE}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
