version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    networks: [roomify]

  frontend:
    build: ./frontend
    environment:
      - VITE_BACKEND_URL=http://127.0.0.1:8080
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks: [roomify]

networks:
  roomify: {}
